### ISSUE TITLE
General Planning (First Issue)

### ISSUE THREAD

**Issue by bradwestfall** [ReactTraining/react-workshop#1]
# Mock App for Fundamentals

This issue is just meant to be a high-level ongoing conversation about the progress of developing the curriculum. 

For anyone working on the fundamentals mock app code directly, [here are some docs](https://github.com/ReactTraining/react-workshop-next/blob/master/docs/yestertech-app.md) regarding how the code is setup and organized

Here's a list of things that still need to be done on the app

## App Features.

Not all of these have to be done, this list is just ideas
- [x] A "view similar products" feature for when we're on a product profile page - #3
- [x] Ratings for the product (star ratings) - #4
- [x] Reach UI combo box for Github username in signup - #5 
- [ ] A11y everywhere. I didn't do much of this while quickly developing - #6
- [x] Finish the checkout process - #7
- [x] Database starting point "seed" - #8
- [ ] Stylize the primary header dropdown (reach ui) menu when clicking avatar - #9
- [x] `<Quantity />` needs to handle input of non-numbers - #10
- [x] Pagination for browsing products - #11
- [x] Sidebar filtering for product browsing - #12
- [x] Initial Database - #13

Also, feel free to keep any personal notes in your clone at `/notes.md`. It's ignored in `.gitignore`
